// <auto-generated>
// Generated by CurrencyManager
// </auto-generated>

using GameMaker.Core.Runtime;

namespace GameMaker.Core.Runtime
{
public class Currency
{
public class Coin
{
    public const string ID = "Coin";
    public BaseCurrencyDefinition GetDefinition()
     {
        return CurrencyManager.Instance.GetDefinition(ID) as BaseCurrencyDefinition;
     }

     public BasePlayerCurrency GetPlayerCurrency()
     {
        return CurrencyGateway.Manager.GetPlayerCurrency("Coin");
     }
}


public class Gem
{
    public const string ID = "Gem";
    public BaseCurrencyDefinition GetDefinition()
     {
        return CurrencyManager.Instance.GetDefinition(ID) as BaseCurrencyDefinition;
     }

     public BasePlayerCurrency GetPlayerCurrency()
     {
        return CurrencyGateway.Manager.GetPlayerCurrency("Gem");
     }
}


public class Energy
{
    public const string ID = "Energy";
    public BaseCurrencyDefinition GetDefinition()
     {
        return CurrencyManager.Instance.GetDefinition(ID) as BaseCurrencyDefinition;
     }

     public BasePlayerCurrency GetPlayerCurrency()
     {
        return CurrencyGateway.Manager.GetPlayerCurrency("Energy");
     }
}


public class Star
{
    public const string ID = "Star";
    public BaseCurrencyDefinition GetDefinition()
     {
        return CurrencyManager.Instance.GetDefinition(ID) as BaseCurrencyDefinition;
     }

     public BasePlayerCurrency GetPlayerCurrency()
     {
        return CurrencyGateway.Manager.GetPlayerCurrency("Star");
     }
}


}
}
