using UnityEngine;

namespace GameMaker.Core.Runtime
{
    [System.Serializable]
    [ScriptableObjectSingletonPathAttribute("Assets/Resources")]
    [CreateAssetMenu(fileName = "CurrencyManager", menuName = "GameMaker/Currency/CurrencyManager")]
    public class CurrencyManager : BaseScriptableObjectDataManager<CurrencyManager, BaseCurrencyDefinition>
    {
#if UNITY_EDITOR
        public string GetGenStringText()
        {
            string ns = GetType().Namespace;

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by CurrencyManager");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using GameMaker.Core.Runtime;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"public class Currency");
            sb.AppendLine("{");
            foreach (var def in GetDefinitions())
            {
                if (string.IsNullOrEmpty(def.GetID())) continue;
                sb.AppendLine(def.GetGenClassCode());
            }
            sb.AppendLine("}");
            sb.AppendLine("}");

            return sb.ToString();
        }
        [ContextMenu("Generate Class")]
        private void GenerateClass()
        {
            string path = "Assets/_Gen/Currency/Scripts/Currency.gen.cs";
            System.IO.Directory.CreateDirectory("Assets/_Gen/Currency/Scripts");
            string code = GetGenStringText();
            System.IO.File.WriteAllText(path, code);
            

            string ns = GetType().Namespace;
            path = $"Assets/_Gen/Currency/{ns}.asmref";

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine("{");
            sb.AppendLine($"    \"reference\": \"{GetType().Assembly.GetName().Name}\"");
            sb.AppendLine("}");
            code = sb.ToString();

            System.IO.File.WriteAllText(path, code);
            UnityEditor.AssetDatabase.Refresh();
        }
#endif
    }
}