using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace GameMaker.Core.Runtime
{
    [ScriptableObjectSingletonPathAttribute("Assets/Resources")]
    [CreateAssetMenu(fileName ="PropertyManager",menuName = "GameMaker/Property/PropertyManager")]
    public class PropertyManager : BaseScriptableObjectDataManager<PropertyManager, PropertyDefinition>
    {
        public List<StatDefinition> GetStats()
        {
            return GetDefinitions().Where(x => x.GetType() == typeof(StatDefinition)).Cast<StatDefinition>().ToList();
        }
        public List<AttributeDefinition> GetAttributes()
        {
            return GetDefinitions().Where(x => x.GetType() == typeof(AttributeDefinition)).Cast<AttributeDefinition>().ToList();
        }

#if UNITY_EDITOR
        public string GetGenStringText()
        {
            string ns = GetType().Namespace;

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by CurrencyManager");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using GameMaker.Core.Runtime;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
             sb.AppendLine($"   public class Property");
            sb.AppendLine("    {");
            foreach (var def in GetDefinitions())
            {
                if (string.IsNullOrEmpty(def.GetID())) continue;

                string className = def.GetName().Replace(" ", "");

                sb.AppendLine(def.GetGenClassCode());

            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
        [ContextMenu("Generate Class")]
        private void GenerateClass()
        {
            string path = "Assets/_Gen/Property/Scripts/Property.gen.cs";
            System.IO.Directory.CreateDirectory("Assets/_Gen/Property/Scripts");
            string code = GetGenStringText();
            System.IO.File.WriteAllText(path, code);
            

            string ns = GetType().Namespace;
            path = $"Assets/_Gen/Property/{ns}.asmref";

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine("{");
            sb.AppendLine($"    \"reference\": \"{GetType().Assembly.GetName().Name}\"");
            sb.AppendLine("}");
            code = sb.ToString();

            System.IO.File.WriteAllText(path, code);
            UnityEditor.AssetDatabase.Refresh();
        }
        [ContextMenu("Add Stat")]
        public void AddStat()
        {
            AddDefinition(new StatDefinition());
        }
        [ContextMenu("Add Attribute")]
        public void AddAttribute()
        {
            AddDefinition(new AttributeDefinition());
        }
#endif
    }
}